// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:5bd7d46e-e420-477e-b063-15055d44e9bb",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_g30XT5PiK",
    "aws_user_pools_web_client_id": "2nll7jr08jeemhuvfjbuj5k50r",
    "aws_cloud_logic_custom": [
        {
            "name": "poctony",
            "endpoint": "https://bz9tghn8h4.execute-api.eu-west-1.amazonaws.com/Prod",
            "region": "eu-west-1"
        }
    ],
    "aws_content_delivery_bucket": "poctony-20181013110120--hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://d7754k6p45y4o.cloudfront.net"
};


export default awsmobile;
